import { describe, expect, it } from "vitest";
import { createDefaultDocument, isValidRoutineDraft, reduceDocument } from "./appState";
describe("application state", () => {
  it("creates the agreed first-launch routine and preferences", () => { expect(createDefaultDocument()).toMatchObject({ schemaVersion: 1, revision: 0, activeRoutineId: "routine-1", preferences: { sound: true, vibration: true }, run: { status: "ready" }, routines: [{ id: "routine-1", name: "Routine 1", cycles: 1, steps: [{ id: "routine-1-step-1", name: "Step 1", durationMs: 60_000 }] }] }); });
  it("rejects an unsaveable routine draft", () => { const routine = createDefaultDocument().routines[0]; expect(isValidRoutineDraft({ ...routine, steps: [] })).toBe(false); expect(isValidRoutineDraft({ ...routine, name: "   " })).toBe(false); expect(isValidRoutineDraft({ ...routine, steps: [{ ...routine.steps[0], durationMs: 0 }] })).toBe(false); });
  it("locks configuration while a run has progress", () => { const document = { ...createDefaultDocument(), run: { status: "paused", elapsedMs: 10_000 } as const }; expect(reduceDocument(document, { type: "set-preference", preference: "sound", value: false })).toBe(document); });
  it("selects the next routine when a saved edit deletes the active routine", () => { const base = createDefaultDocument(); const routines = [base.routines[0], { ...base.routines[0], id: "routine-2", name: "Routine 2" }, { ...base.routines[0], id: "routine-3", name: "Routine 3" }]; const result = reduceDocument({ ...base, routines, activeRoutineId: "routine-2" }, { type: "commit-routines", routines: [routines[0], routines[2]] }); expect(result.activeRoutineId).toBe("routine-3"); });
  it("starts the active routine through the application reducer", () => { expect(reduceDocument(createDefaultDocument(), { type: "run-command", command: { type: "start", nowMs: 2_000 } })).toMatchObject({ revision: 1, run: { status: "running", anchorTimeMs: 2_000, elapsedBeforeAnchorMs: 0 } }); });
  it("commits immediate cycle settings for the active routine", () => { const result = reduceDocument(createDefaultDocument(), { type: "set-cycles", cycles: 7 }); expect(result.routines[0].cycles).toBe(7); expect(result.revision).toBe(1); });
  it("selects and persists another routine while ready", () => { const base = createDefaultDocument(); const second = { ...base.routines[0], id: "routine-2", name: "Routine 2" }; const result = reduceDocument({ ...base, routines: [...base.routines, second] }, { type: "select-routine", routineId: second.id }); expect(result.activeRoutineId).toBe(second.id); });
  it("normalizes names when edits are saved", () => { const base = createDefaultDocument(); const edited = { ...base.routines[0], name: "  Morning intervals  ", steps: [{ ...base.routines[0].steps[0], name: "  Focus  " }] }; const result = reduceDocument(base, { type: "commit-routine", routine: edited }); expect(result.routines[0]).toMatchObject({ name: "Morning intervals", steps: [{ name: "Focus" }] }); });
});
