export const strings = {
  appName: "The Counter",
  reset: "Reset",
  manageRoutines: "Manage routines",
  editRoutine: "Edit routine",
  cycles: "Cycles",
  start: "Start",
  pause: "Pause",
  resume: "Resume",
  completed: "Completed",
  saveRoutine: "Save routine",
  cancel: "Cancel",
  addStep: "Add timed step",
  routineName: "Routine name",
  close: "Close",
  edit: "Edit",
  save: "Save",
  preferences: "Preferences",
  sound: "Sound",
  vibration: "Vibration",
  addRoutine: "Add routine",
  downloadDiagnostic: "Download diagnostic data",
  resetApp: "Reset app",
  retry: "Retry",
} as const;
